authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

django_gb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='basic')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('orderapp.urls', namespace='orders')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),

    path('social/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contact, name='contact'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('product/<int:pk>/', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    image = models.ImageField(upload_to='product-img', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.category_id})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        # ordering = ['name']

mainapp/views.py
import random

from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product


def index(request):
    contex = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', contex)


def get_hot_product():
    product_ids = Product.objects.values_list('id', flat=True).all()
    product_id = random.choice(product_ids)
    return Product.objects.get(pk=product_id)


def same_product(hot_product):
    return Product.objects.filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:3]


def products(request):
    products = Product.objects.all()[:3]
    hot_product = get_hot_product()
    contex = {'page_title': 'продукты',
              'products': products,
              'hot_product': hot_product,
              'same_product': same_product(hot_product),
              }
    return render(request, 'mainapp/products.html', contex)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    contex = {'page_title': 'страница товара',
              'product': product,
              }
    return render(request, 'mainapp/product_page.html', contex)


def category(request, pk):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все'}
        products = Product.objects.all()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.all()

    products_paginator = Paginator(products, 3)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {'page_title': 'товары категории',
               'products': products,
               'category': category,
               }

    return render(request, 'mainapp/products_category.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': 88003331122,
            'email': 'msk@mail.ru',
            'address': 'В пределах МКАД'
        },
        {
            'city': 'Cанкт-Петербург',
            'phone': 88123331111,
            'email': 'spb@mail.ru',
            'address': 'В пределах КАД'},
        {
            'city': 'Иркутск',
            'phone': 830123333333,
            'email': 'irk@mail.ru',
            'address': 'В пределах центра'}
    ]
    contex = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contact.html', contex)

mainapp/templates/mainapp/includes/inc_menu.html
<div class="header clearfix">
    <a href="{% url 'basic:index' %}" class="logo"></a>
    <ul class="menu">
        <li>
            <a href="{% url 'basic:index' %}"
               class='{% if request.resolver_match.url_name == 'index' %}active{% endif %}'>
                домой
            </a>
        </li>
        <li>
            <a href="{% url 'basic:products' %}"
               class='{% if request.resolver_match.url_name == 'products' or request.resolver_match.url_name == 'category' %}active{% endif %}'>
                продукты</a>
        </li>
        <li>
            <a href="{% url 'basic:contact' %}"
               class='{% if request.resolver_match.url_name == 'contact' %}active{% endif %}'>
                контакты
            </a>
        </li>
        <li>
            {% if user.is_authenticated %}
                <li>
                    <div class="dropdown">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                            {{ user.first_name|title|default:'пользователь' }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'auth:edit' %}">
                                    профиль
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'orders:index' %}">
                                    заказы
                                </a>
                            </li>
                        </ul>
                    </div>
                </li>
            {% endif %}
        </li>
        {% if user.is_superuser %}
            <li>
                <a href="{% url 'new_admin:index' %}">
                    Админка
                </a>
            </li>
        {% endif %}
        <li>
            {% if user.is_authenticated %}
                <a href="{% url 'auth:logout' %}">
                    выйти
                </a>
            {% else %}
                <a href="{% url 'auth:login' %}">
                    войти
                </a>
            {% endif %}
        </li>
    </ul>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:index' %}" class="basket">
        {% if user.is_authenticated %}
            <span>{{ user.basket_price|floatformat:0 }} руб ({{ user.basket_qty }} шт)</span>
        {% endif %}
    </a>
</div>

mainapp/templates/mainapp/includes/menu_catalog.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'basic:category' 0 %}"
            class='{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == 0 %}active{% endif %}'>
                все
            </a>
        </li>

        {% for category in categories %}
            <li>
                <a href="{% url 'basic:category' category.pk %}"
                class='{% if request.resolver_match.url_name == 'category' and request.resolver_match.kwargs.pk == category.pk %}active{% endif %}'>
                    {{ category.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>