authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.index, name='index'),
    path('add_to/<int:product_pk>/', basketapp.add_to, name='add_to'),
    path('delete/<int:basket_item_pk>/', basketapp.delete, name='delete'),
    path('update/<int:basket_item_pk>/<int:qty>/', basketapp.update),
]

django_gb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('mainapp.urls', namespace='basic')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('orders/', include('orderapp.urls', namespace='orders')),
    path('new/admin/', include('adminapp.urls', namespace='new_admin')),

    path('social/', include('social_django.urls', namespace='social')),

    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('products/', mainapp.products, name='products'),
    path('contact/', mainapp.contact, name='contact'),
    path('category/<int:pk>/', mainapp.category, name='category'),
    path('product/<int:pk>/', mainapp.product_page, name='product_page'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def delete(self, using=None, keep_parents=False):
        self.is_active = False
        self.save(using=using)


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField('название', max_length=64)
    description = models.TextField('описание', blank=True)
    short_desc = models.CharField('краткое описание', max_length=200, blank=True)
    image = models.ImageField(upload_to='product-img', blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField('количество на складе', default=0)
    is_active = models.BooleanField('активность', default=True)

    def __str__(self):
        return f'{self.name} ({self.category_id})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        # ordering = ['name']

mainapp/views.py
import random

from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.shortcuts import render, get_object_or_404
from .models import ProductCategory, Product


def index(request):
    contex = {
        'page_title': 'главная',
    }
    return render(request, 'mainapp/index.html', contex)


def get_hot_product():
    product_ids = Product.objects.values_list('id', flat=True).all()
    product_id = random.choice(product_ids)
    return Product.objects.get(pk=product_id)


def same_product(hot_product):
    return Product.objects.filter(category=hot_product.category). \
               exclude(pk=hot_product.pk)[:3]


def products(request):
    products = Product.objects.all()[:3]
    hot_product = get_hot_product()
    contex = {'page_title': 'продукты',
              'products': products,
              'hot_product': hot_product,
              'same_product': same_product(hot_product),
              }
    return render(request, 'mainapp/products.html', contex)


def product_page(request, pk):
    product = get_object_or_404(Product, pk=pk)
    contex = {'page_title': 'страница товара',
              'product': product,
              }
    return render(request, 'mainapp/product_page.html', contex)


def category(request, pk):
    page_num = request.GET.get('page', 1)
    if pk == 0:
        category = {'pk': 0, 'name': 'все'}
        products = Product.objects.all()
    else:
        category = get_object_or_404(ProductCategory, pk=pk)
        products = category.product_set.all()

    products_paginator = Paginator(products, 3)
    try:
        products = products_paginator.page(page_num)
    except PageNotAnInteger:
        products = products_paginator.page(1)
    except EmptyPage:
        products = products_paginator.page(products_paginator.num_pages)

    context = {'page_title': 'товары категории',
               'products': products,
               'category': category,
               }

    return render(request, 'mainapp/products_category.html', context)


def contact(request):
    locations = [
        {
            'city': 'Москва',
            'phone': 88003331122,
            'email': 'msk@mail.ru',
            'address': 'В пределах МКАД'
        },
        {
            'city': 'Cанкт-Петербург',
            'phone': 88123331111,
            'email': 'spb@mail.ru',
            'address': 'В пределах КАД'},
        {
            'city': 'Иркутск',
            'phone': 830123333333,
            'email': 'irk@mail.ru',
            'address': 'В пределах центра'}
    ]
    contex = {
        'page_title': 'контакты',
        'locations': locations,
    }
    return render(request, 'mainapp/contact.html', contex)

mainapp/templates/mainapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>
        {{ page_title|capfirst }}
        {% now "d.m.y H:i" %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>

<div class="container">

    {% block centerblock %}
    {% endblock %}

    <div class="clr"></div>

</div>

<div class="footer">
    <div class="clearfix">
        <div class="text-footer">
            <h3>контакты</h3>
        </div>
        <div class="text-footer">
            <h3>полезная информация</h3>
        </div>
        <div class="text-footer clearfix">
            <h3>Оставайтесь на связи</h3>
            <p>Подписаться на новости и рассылки</p>
            <form>
                <input type="email" name="email" placeholder="ваш email">
                <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
            </form>
        </div>
    </div>
    <p class="small">&copy; GB 2017</p>
    <div class="social">
        <a href="#" class="social1"></a>
        <a href="#" class="social2"></a>
        <a href="#" class="social3"></a>
        <a href="#" class="social4"></a>
    </div>
    <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
</div>

</body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block centerblock %}
    <div class="hero">
        {% include 'mainapp/includes/inc_menu.html' %}
        <h1>наши контакты</h1>
    </div>
    <div class="location">
        {% for locations in locations %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ locations.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ locations.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ locations.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ locations.address }}</p>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block centerblock %}
    <div class="slider">
        {% include 'mainapp/includes/inc_menu.html' %}
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="/static/img/arrow.png" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            <div class="block">
                <a href="#"><img src="/static/img/product-1.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="img">
                        <h4>Отличный стул</h4>
                        <p>Расположитесь комфортно. </p>
                    </div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="/static/img/product-2.jpg" alt="">
                    <div class="text">
                        <img src="/static/img/icon-hover.png" alt="">
                        <h4>Стул повышенного качества</h4>
                        <p>Не оторваться. </p>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}



mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block centerblock %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <div class="details">
        {% include 'mainapp/includes/menu_catalog.html' %}
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="{% url 'basket:add_to' product.pk %}"><img src="/media/{{ product.image }}"
                                                                            alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'basket:add_to' product.pk %}"><img src="/media/{{ product.image }}"
                                                                            alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'basket:add_to' product.pk %}"><img src="/media/{{ product.image }}"
                                                                            alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name }}</h3>
                <br>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add_to' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block centerblock %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc_menu.html' %}
    </div>
    <div class="details">
        {% include 'mainapp/includes/menu_catalog.html' %}
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="/media/{{ hot_product.image }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="{% url 'basket:add_to' hot_product.pk %}"><img src="/media/{{ hot_product.image }}"
                                                                                alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'basket:add_to' hot_product.pk %}"><img src="/media/{{ hot_product.image }}"
                                                                                alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="{% url 'basket:add_to' hot_product.pk %}"><img src="/media/{{ hot_product.image }}"
                                                                                alt="slider">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add_to' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.short_desc }}</p>
                </div>
            </div>
        </div>
        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="/static/img/arrow.png" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_product %}
                    <div class="block">
                        <a href="{% url 'basic:product_page' product.pk %}">
                            <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <h3>{{ product.category.name }}</h3>
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}




mainapp/templates/mainapp/products_category.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block centerblock %}
    <div class="hero-white">
        {% include 'mainapp/includes/inc_menu.html' %}

    </div>
    <div class="details">
        {% include 'mainapp/includes/menu_catalog.html' %}

        <div class="details-products">
            <div class="related">
                <div class="title clearfix">
                    <h2>Продукты категории {{ category.name|upper }}</h2>
                    <div class="paginator">
                        {% if products.has_previous %}
                            <a href="{% url 'basic:category' category.pk %}?page={{ products.previous_page_number }}">
                                <
                            </a>
                        {% endif %}
                        <span class="current">страница {{ products.number }} из {{ products.paginator.num_pages }}</span>
                        {% if products.has_next %}
                            <a href="{% url 'basic:category' category.pk %}?page={{ products.next_page_number }}">
                                >
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="related-products clearfix">
                    {% for product in products %}
                        <div class="block">
                            <a href="{% url 'basic:product_page' product.pk %}">
                                <img src="/media/{{ product.image }}" alt="">
                                <div class="text">
                                    <img src="/static/img/icon-hover.png" alt="img">
                                    <h4>{{ product.name }}</h4>
                                    <p>{{ product.short_desc }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}